title: A Muslim''s Notes
description: A Muslim puts his notes in a just-the-docs themed jerkyl website.
theme: just-the-docs

url: https://friedegg796.github.io/amuslimsnotes/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
