title: A Muslim's Notes
description: A Muslim puts his notes in a just-the-docs themed jekyll website.
theme: just-the-docs
color_scheme: dark

url: https://friedegg796.github.io/amuslimsnotes/

aux_links:
  My portfolio: https://friedegg796.github.io/
